export const browserCoreExamples = [
  "penguin browser status",
  "penguin browser start",
  "penguin browser stop",
  "penguin browser tabs",
  "penguin browser open https://example.com",
  "penguin browser focus abcd1234",
  "penguin browser close abcd1234",
  "penguin browser screenshot",
  "penguin browser screenshot --full-page",
  "penguin browser screenshot --ref 12",
  "penguin browser snapshot",
  "penguin browser snapshot --format aria --limit 200",
  "penguin browser snapshot --efficient",
  "penguin browser snapshot --labels",
];

export const browserActionExamples = [
  "penguin browser navigate https://example.com",
  "penguin browser resize 1280 720",
  "penguin browser click 12 --double",
  'penguin browser type 23 "hello" --submit',
  "penguin browser press Enter",
  "penguin browser hover 44",
  "penguin browser drag 10 11",
  "penguin browser select 9 OptionA OptionB",
  "penguin browser upload /tmp/file.pdf",
  'penguin browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "penguin browser dialog --accept",
  'penguin browser wait --text "Done"',
  "penguin browser evaluate --fn '(el) => el.textContent' --ref 7",
  "penguin browser console --level error",
  "penguin browser pdf",
];
