#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${PENGUIN_INSTALL_E2E_IMAGE:-${PENGUIN_INSTALL_E2E_IMAGE:-penguin-install-e2e:local}}"
INSTALL_URL="${PENGUIN_INSTALL_URL:-${PENGUIN_INSTALL_URL:-https://penguin.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
PENGUIN_E2E_MODELS="${PENGUIN_E2E_MODELS:-${PENGUIN_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e PENGUIN_INSTALL_URL="$INSTALL_URL" \
  -e PENGUIN_INSTALL_TAG="${PENGUIN_INSTALL_TAG:-${PENGUIN_INSTALL_TAG:-latest}}" \
  -e PENGUIN_E2E_MODELS="$PENGUIN_E2E_MODELS" \
  -e PENGUIN_INSTALL_E2E_PREVIOUS="${PENGUIN_INSTALL_E2E_PREVIOUS:-${PENGUIN_INSTALL_E2E_PREVIOUS:-}}" \
  -e PENGUIN_INSTALL_E2E_SKIP_PREVIOUS="${PENGUIN_INSTALL_E2E_SKIP_PREVIOUS:-${PENGUIN_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
